export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const OPEN_THE_TASK_WINDOW = 'OPEN_THE_TASK_WINDOW';
export const CURRENT_USER = 'CURRENT_USER';
export const CORRECT_LOGIN = 'CORRECT_LOGIN';
export const CURRENT_TASK_DATA = 'CURRENT_TASK_DATA';
export const CURRENT_PROJECT_DATA = 'CURRENT_PROJECT_DATA';
export const CORRECT_TOKEN = 'CORRECT_TOKEN';